[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  functions = "netlify/functions"
  port = 8888
  targetPort = 5173
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# command: runs Vite's production build
# publish: Vite builds to the dist folder
# functions: tells Netlify where your serverless code lives
# redirects: allows API calls to work cleanly via /functions/*